name: academia_chatbot_backend
description: Backend application for Chatbot
version: 0.0.1
author: Feroz Ahmmed <froghramar@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  mongo_dart: ^0.3.3
  safe_config: ^2.0.1
  jaguar_jwt: ^2.1.5
  password: ^0.1.1+2

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0